baseURL = "https://awesome-fork.surge.sh/"
languageCode = "en-us"
title = "Tiffany Hooton Therapy Long  Beach"
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "/couples-therapy-long-beach/"
name = "Couples Therapy"
weight = 2
[[menu.main]]
URL = "/self-esteem-therapy-long-beach/"
name = "Self Esteem"
weight = 3
[[menu.main]]
URL = "/transgender-therapy-long-beach/"
name = "Gender Therapy"
weight = 4
[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 5
[params]
