baseURL = "https://tiffanyhootonmft.com/"
languageCode = "en-us"
title = "Tiffany Hooton Therapy"
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "/#services"
name = "Services"
weight = 2
[[menu.main]]
URL = "/#about-me"
name = "About"
weight = 3
[[menu.main]]
URL = "/partner-perspectives/"
name = "Partner Perspectives"
weight = 4
[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 5
[params]
accentColor = "#6C80FD"
address = "851 Pine Ave, #102, Long Beach, CA 90813"
addressLink = "https://www.google.com/maps/place/851+Pine+Ave+%23102,+Long+Beach,+CA+90813/@33.777548,-118.194746,17z/data=!3m1!4b1!4m5!3m4!1s0x80dd3146727b2c67:0xbe4a52b19508031!8m2!3d33.7775436!4d-118.1925573?shorturl=1"
bodyImage = "/assets/images/mountains.jpg"
email = "TiffanyHootonTherapy@protonmail.com"
fontsEmbed = "<link href=\"https://fonts.googleapis.com/css?family=Lato|Poppins&display=swap\" rel=\"stylesheet\">"
headerFont = "Poppins"
heroImage = "/assets/images/waves.jpg"
mainFont = "Lato"
phone = "714-500-7756"
psychToday = "https://www.psychologytoday.com/us/therapists/tiffany-hooton-long-beach-ca/703413?sid=5d9d09a0f10f3"
themeColor = "#4A90E2"
