baseURL = "https://awesome-fork.surge.sh/"
languageCode = "en-us"
title = "Tiffany Hooton Therapy"
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "/#services"
name = "Services"
weight = 2
[[menu.main]]
URL = "/#about-me"
name = "About"
weight = 3
[[menu.main]]
URL = "/partner-perspectives/"
name = "Partner Perspectives"
weight = 4
[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 5
[params]
